# Generated by Django 5.0.6 on 2024-07-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='productos_ids',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_producto', to='tienda.orden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
